### ISSUE TITLE
Consider releasing

### ISSUE THREAD

**Issue by BuonOmo** [michaelherold/benchmark-memory#22]
Hey, the fact that benchmark-memory (from rubygem) still has `memory_profiler ~> 0.9` in its dependencies is really cumbersome (conflicts with other gems). The last release is 2017, do you consider a new release at some point ?

**Comment by michaelherold** [comment]
Thanks for the push! I just shipped a new feature that I had sitting for who knows how long. Enjoy v0.2.0!

**Comment by BuonOmo** [comment]
Blazing fast, thank you :heart:
